import Transaction from '../models/Transaction.js';import Subscription from '../models/Subscription.js'
const monthRange=(month)=>{const d=month?new Date(`${month}-01T00:00:00`):new Date();const s=new Date(d.getFullYear(),d.getMonth(),1),e=new Date(d.getFullYear(),d.getMonth()+1,1);return{s,e}}
export const transactions=async(req,res)=>res.json(await Transaction.find({user:req.user}).sort({date:-1}))
export const addTransaction=async(req,res)=>res.status(201).json(await Transaction.create({...req.body,user:req.user}))
export const deleteTransaction=async(req,res)=>{await Transaction.deleteOne({_id:req.params.id,user:req.user});res.json({message:'Deleted'})}
export const subscriptions=async(req,res)=>res.json(await Subscription.find({user:req.user}).sort({nextBillingDate:1}))
export const addSubscription=async(req,res)=>res.status(201).json(await Subscription.create({...req.body,user:req.user}))
export const deleteSubscription=async(req,res)=>{await Subscription.deleteOne({_id:req.params.id,user:req.user});res.json({message:'Deleted'})}
export const chargeSubscription=async(req,res)=>{const s=await Subscription.findOne({_id:req.params.id,user:req.user});if(!s)return res.status(404).json({message:'Subscription not found'});const now=new Date(),key=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;if(s.lastAddedMonth===key)return res.status(400).json({message:'Already added for this month'});const t=await Transaction.create({user:req.user,type:'expense',account:s.account,amount:s.amount,category:s.category,description:`${s.name} subscription`,date:now,subscription:s._id});s.lastAddedMonth=key;await s.save();res.status(201).json(t)}
export const summary=async(req,res)=>{const{s,e}=monthRange(req.query.month);const tx=await Transaction.find({user:req.user,date:{$gte:s,$lt:e}});const income=tx.filter(x=>x.type==='income').reduce((a,x)=>a+x.amount,0),expense=tx.filter(x=>x.type==='expense').reduce((a,x)=>a+x.amount,0);const subs=tx.filter(x=>x.type==='expense'&&x.subscription).reduce((a,x)=>a+x.amount,0);const categories={};tx.filter(x=>x.type==='expense').forEach(x=>categories[x.category]=(categories[x.category]||0)+x.amount);res.json({income,expense,subscriptions:subs,net:income-expense,categories,transactions:tx})}
